Feature/movie page
skss-1/vue-internship pull request #24
Opened 2022-09-03 12:46 UTC by nikitius20

2022-09-05 16:06 UTC, skss-1 requested changes

2022-09-05 16:06 UTC, skss-1 commented on src/components/MovieCard.vue
> +    class="movie-card col-lg-2 col-md-2 col-sm-3 col-5 m-3 p-0"
Because it's clickable, this element should have `cursor: pointer`

2022-09-05 16:06 UTC, skss-1 commented on src/components/CreditsScroll.vue
> +      <img
Image should have the same size, even when it's not loaded
![image](https://user-images.githubusercontent.com/110411952/188482469-41541eaa-0adf-4b38-83ed-4b29c37fcaca.png)

2022-09-05 16:06 UTC, skss-1 commented on src/components/CreditsScroll.vue
> +
Redundant empty line

2022-09-05 16:06 UTC, skss-1 commented on src/components/CreditsScroll.vue
> +  <div class="credits my-3">
Selector of the root element should be the same as component name.

2022-09-05 16:06 UTC, skss-1 commented on src/views/MoviePageView.vue
> +        let date=`${month[+this.item.release_date.slice(5,7) -1]} ${+this.item.release_date.slice(8,10)} ${this.item.release_date.slice(0,4)}`
It's ok to have an array for months for some cases. But not ok to parse date from string.

Better to use `Date` object. You should parse and create the date at first: `const releaseDate = new Date(Date.parse(this.item.release_date))`.
Then return the needed format using the Date object methods: `return releaseDate.toLocaleString('en', { dateStyle: 'long' })`

2022-09-05 16:06 UTC, skss-1 commented on src/views/MoviePageView.vue
> +      return `https://image.tmdb.org/t/p/original${this.item.poster_path}`
`https://image.tmdb.org/t/p/original` already stored in the `tmdb-api.js` file. Please use it from there.
*Note:* the same for 'backgroundUrl'

2022-09-05 16:06 UTC, skss-1 commented on src/router/index.js
>      path: '/about',
Please, remove this route and `AboutView` because it is redundant

2022-09-05 16:06 UTC, skss-1 commented on src/router/index.js
> +    component: MoviePageView,
It's not required for now, but better to use the `import()` functions for routes. As example you can see how it made for `/about` route

2022-09-05 16:06 UTC, skss-1 commented on src/components/MovieCard.vue
> +    @click="goToMoviePage"
For better navigation, I suggest to add `tabindex="0"` for the root element. Also add event handlers for `@keydown.enter.esc="goToMoviePage"`. User will have possibility to navigate through the cards via keyboard

2022-09-06 10:58 UTC, nikitius20 commented on src/views/MoviePageView.vue
> +        let date=`${month[+this.item.release_date.slice(5,7) -1]} ${+this.item.release_date.slice(8,10)} ${this.item.release_date.slice(0,4)}`
Thx, I didn't even knew about this

2022-09-06 21:29 UTC, skss-1 approved these changes

2022-09-06 21:36 UTC, merged